//
// Created by demu9 on 3/13/2020.
//

#ifndef ASD_ESERCITAZIONE_BINARYSEARCH_01_TESTDATAGENERATION_H
#define ASD_ESERCITAZIONE_BINARYSEARCH_01_TESTDATAGENERATION_H
#define MAX_RAND 1000

int* generateSortedArrayOfInt(int size);

#endif //ASD_ESERCITAZIONE_BINARYSEARCH_01_TESTDATAGENERATION_H
