//
// Created by SimonD on 6/1/2020.
//

#ifndef LEZ11_ASD_ESERCITAZIONE_QUICKINSERTIONSORT_INSERTIONSORT_H
#define LEZ11_ASD_ESERCITAZIONE_QUICKINSERTIONSORT_INSERTIONSORT_H


void insertionSort(int lista[], int dim);

#endif //LEZ11_ASD_ESERCITAZIONE_QUICKINSERTIONSORT_INSERTIONSORT_H
