#include <stdio.h>
#include "models.h"
#include "BinarySearch.h"

int main() {
    int foundIndex = 0;
    // List of Mock data Autogenerated
    Hotel hotels[] = {
            {"Abamar",                        40, 4},
            {"Altura",                        50, 5},
            {"Centrale",                      10, 3},
            {"Flamingo",                      30, 4},
            {"Sant Efis",                     20, 2},
            {"Tanka Village",                 40, 3},
    };

    // performing a simple search
    foundIndex = binaryIterativeSearch(hotels,"Altura", 6);
    printf("hotel s fount index: %d", foundIndex);

    return 0;
}