#include <stdio.h>
#include "models.h"
#include "BinarySearch.h"

int main() {
    int foundIndex = 0;
    // List of Mock data Autogenerated
    Hotel hotels[] = {
            {"Jolly Hotel ",                  50, 5},
            {"Hotel su Nuraxi",               30, 3},
            {"Centrale",                      10, 3},
            {"I G.V. Club Santa Giusta",      20, 3},
            {"Chia Laguna Grand Hotel",       50, 3},
            {"Tarthes Hotel",                 20, 3},
            {"Calaserena Village",            20, 5},
            {"Villaggio Colostrai",           10, 5},
            {"Albaruja",                      40, 5},
            {"Free Beach Club Villaggio",     20, 4},
            {"La Ghinghetta",                 30, 4},
            {"Castello ",                     50, 4},
            {"Abamar",                        40, 4},
            {"Hotel Baia di Nora",            30, 4},
            {"Costa dei Fiori",               20, 4},
            {"Flamingo",                      30, 4},
            {"Is Molas Golf",                 50, 4},
            {"Is Morus Relais",               40, 5},
            {"Rocca Dorada",                  50, 5},
            {"Sant Efis",                     20, 2},
            {"Forte Village Le palme",        20, 2},
            {"Mare Pineta",                   30, 2},
            {"Panorama Hotel",                40, 2},
            {"Califfo",                       50, 5},
            {"Grand Hotel Quattro Torri",     20, 5},
            {"Hotel Setar",                   30, 5},
            {"I Ginepri Ristorante",          50, 4},
            {"Eden",                          20, 4},
            {"Delle Terme",                   50, 4},
            {"La Lanterna Verde",             40, 4},
            {"Hinterland",                    50, 4},
            {"Baia delle Ginestre Residence", 30, 4},
            {"Capo Boi Grand",                50, 5},
            {"Cormoran",                      50, 5},
            {"Simius Playa",                  20, 1},
            {"Sofitel Timi Ama",              50, 2},
            {"Tanka Village",                 40, 3},
            {"Altura",                        50, 5}
    };

    // performing a simple search
    foundIndex = binaryIterativeSearch(hotels,"Tanka Village", 38);
    printf("hotel s fount index: %d", foundIndex);

    return 0;
}